# PilotApp v1 – Credentials (PLACEHOLDERS ONLY)
# Do NOT commit real credentials here

AEGIR_USER = ""
AEGIR_PASS = ""

PUSHOVER_APP_TOKEN = ""
PUSHOVER_USER_KEY = ""

GOOGLE_DRIVE_CREDENTIALS_PATH = ""
GOOGLE_DRIVE_TOKEN_PATH = ""

GITHUB_TOKEN = ""
